name: aidea test

# Workflow is triggers on pushes to repository
on:
  pull_request:
    branches: [ mainline ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
            node-version: 12
        
      - run: npm install
      - run: touch src/aws-exports.js
      - run: echo "{}" >> src/aws-exports.js
      - run: npm test